---

# Main tasks file for yarn role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::yarn'
    - 'role::yarn::init'


- name: 'INSTALL | Manage OS family installation tasks'
  become: True
  include: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::yarn'
    - 'role::yarn::install'
